### ISSUE TITLE
Rename Subscription to Subscriotions

### ISSUE THREAD

**Issue by svenl77** [Themekraft/wc4bp-subscriptions#4]
I have already changed the repository name. Please change also the code function and variable names etc. in the code to stay consistent.

The core Plugin is called WooCommerce Subscriptions so we should also use the "s" == Subscriptions

**Comment by gfirem** [comment]
https://github.com/Themekraft/wc4bp-subscriptions/commit/3a7c8ae7818f6c3a60b32662da6523eea584d27a
