### ISSUE TITLE
This theme requires the following plugin: WC4BP -> WooCommerce BuddyPress Integration. Begin installing plugin

### ISSUE THREAD

**Issue by svenl77** [Themekraft/wc4bp-subscriptions#6]
even its activated and working

**Comment by svenl77** [comment]
and if I try to activate: Something went wrong with the plugin API.

**Comment by gfirem** [comment]
https://github.com/Themekraft/wc4bp-subscriptions/commit/3a7c8ae7818f6c3a60b32662da6523eea584d27a
